name: Linting

on: pull_request

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: composer install
      run: composer install
    - name: PHPCS check
      uses: chekalsky/phpcs-action@v1
      with:
        enable_warnings: true
        phpcs_bin_path: './vendor/bin/phpcs'
